// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getChartDataByDay = `-- name: GetChartDataByDay :many
SELECT
  gs.period_start,
  COALESCE(COUNT(DISTINCT p.visitor_id), 0)::bigint AS visitors,
  COALESCE(COUNT(p.id), 0)::bigint AS views
FROM generate_series($2::timestamptz, $3::timestamptz - interval '1 day', interval '1 day') AS gs(period_start)
LEFT JOIN pageviews p
  ON p.website_id = $1
  AND p.created_at >= gs.period_start
  AND p.created_at < gs.period_start + interval '1 day'
GROUP BY gs.period_start
ORDER BY gs.period_start ASC
`

type GetChartDataByDayParams struct {
	WebsiteID uuid.UUID
	Column2   time.Time
	Column3   time.Time
}

type GetChartDataByDayRow struct {
	PeriodStart interface{}
	Visitors    int64
	Views       int64
}

// Returns daily buckets of visitors and views, including empty buckets (0).
// Use for: last 7 days (7 bars), this week (7 bars), this month (28-31 bars),
//
//	last 30 days (30 bars), last 90 days (90 bars), custom range > 2 days.
func (q *Queries) GetChartDataByDay(ctx context.Context, arg GetChartDataByDayParams) ([]GetChartDataByDayRow, error) {
	rows, err := q.db.Query(ctx, getChartDataByDay, arg.WebsiteID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChartDataByDayRow
	for rows.Next() {
		var i GetChartDataByDayRow
		if err := rows.Scan(&i.PeriodStart, &i.Visitors, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChartDataByHour = `-- name: GetChartDataByHour :many
SELECT
  gs.period_start,
  COALESCE(COUNT(DISTINCT p.visitor_id), 0)::bigint AS visitors,
  COALESCE(COUNT(p.id), 0)::bigint AS views
FROM generate_series($2::timestamptz, $3::timestamptz - interval '1 hour', interval '1 hour') AS gs(period_start)
LEFT JOIN pageviews p
  ON p.website_id = $1
  AND p.created_at >= gs.period_start
  AND p.created_at < gs.period_start + interval '1 hour'
GROUP BY gs.period_start
ORDER BY gs.period_start ASC
`

type GetChartDataByHourParams struct {
	WebsiteID uuid.UUID
	Column2   time.Time
	Column3   time.Time
}

type GetChartDataByHourRow struct {
	PeriodStart interface{}
	Visitors    int64
	Views       int64
}

// Returns hourly buckets of visitors and views, including empty buckets (0).
// Use for: last 24 hours (24 bars), custom range <= 2 days (up to 48 bars).
func (q *Queries) GetChartDataByHour(ctx context.Context, arg GetChartDataByHourParams) ([]GetChartDataByHourRow, error) {
	rows, err := q.db.Query(ctx, getChartDataByHour, arg.WebsiteID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChartDataByHourRow
	for rows.Next() {
		var i GetChartDataByHourRow
		if err := rows.Scan(&i.PeriodStart, &i.Visitors, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChartDataByMonth = `-- name: GetChartDataByMonth :many
SELECT
  gs.period_start,
  COALESCE(COUNT(DISTINCT p.visitor_id), 0)::bigint AS visitors,
  COALESCE(COUNT(p.id), 0)::bigint AS views
FROM generate_series($2::timestamptz, $3::timestamptz - interval '1 month', interval '1 month') AS gs(period_start)
LEFT JOIN pageviews p
  ON p.website_id = $1
  AND p.created_at >= gs.period_start
  AND p.created_at < gs.period_start + interval '1 month'
GROUP BY gs.period_start
ORDER BY gs.period_start ASC
`

type GetChartDataByMonthParams struct {
	WebsiteID uuid.UUID
	Column2   time.Time
	Column3   time.Time
}

type GetChartDataByMonthRow struct {
	PeriodStart interface{}
	Visitors    int64
	Views       int64
}

// Returns monthly buckets of visitors and views, including empty buckets (0).
// Use for: this year (12 bars).
func (q *Queries) GetChartDataByMonth(ctx context.Context, arg GetChartDataByMonthParams) ([]GetChartDataByMonthRow, error) {
	rows, err := q.db.Query(ctx, getChartDataByMonth, arg.WebsiteID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChartDataByMonthRow
	for rows.Next() {
		var i GetChartDataByMonthRow
		if err := rows.Scan(&i.PeriodStart, &i.Visitors, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetrics = `-- name: GetMetrics :one
SELECT
  -- current period
  (SELECT COUNT(DISTINCT visitor_id)::bigint
   FROM pageviews pv
   WHERE pv.website_id = $1 AND pv.created_at >= $2 AND pv.created_at < $3) AS visitors,
  (SELECT COUNT(*)::bigint
   FROM visits v
   WHERE v.website_id = $1 AND v.started_at >= $2 AND v.started_at < $3) AS visits,
  (SELECT COUNT(*)::bigint
   FROM pageviews pv
   WHERE pv.website_id = $1 AND pv.created_at >= $2 AND pv.created_at < $3) AS views,
  (SELECT COALESCE(
     ROUND(AVG(EXTRACT(EPOCH FROM (ended_at - started_at))))::bigint,
     0
   )
   FROM visits v
   WHERE v.website_id = $1 AND v.started_at >= $2 AND v.started_at < $3) AS avg_duration_seconds,
  -- previous period (for % change comparison)
  (SELECT COUNT(DISTINCT visitor_id)::bigint
   FROM pageviews pv
   WHERE pv.website_id = $1 AND pv.created_at >= $4 AND pv.created_at < $5) AS prev_visitors,
  (SELECT COUNT(*)::bigint
   FROM visits v
   WHERE v.website_id = $1 AND v.started_at >= $4 AND v.started_at < $5) AS prev_visits,
  (SELECT COUNT(*)::bigint
   FROM pageviews pv
   WHERE pv.website_id = $1 AND pv.created_at >= $4 AND pv.created_at < $5) AS prev_views,
  (SELECT COALESCE(
     ROUND(AVG(EXTRACT(EPOCH FROM (ended_at - started_at))))::bigint,
     0
   )
   FROM visits v
   WHERE v.website_id = $1 AND v.started_at >= $4 AND v.started_at < $5) AS prev_avg_duration_seconds
`

type GetMetricsParams struct {
	WebsiteID   uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	CreatedAt_3 time.Time
	CreatedAt_4 time.Time
}

type GetMetricsRow struct {
	Visitors               int64
	Visits                 int64
	Views                  int64
	AvgDurationSeconds     interface{}
	PrevVisitors           int64
	PrevVisits             int64
	PrevViews              int64
	PrevAvgDurationSeconds interface{}
}

// Returns stats for a date range plus the previous period of equal length for comparison.
// $1 = website_id
// $2 = current_start, $3 = current_end (exclusive)
// $4 = prev_start,    $5 = prev_end    (exclusive)
// The caller computes prev_start/prev_end: e.g. for last 7 days,
//
//	current = [now-7d, now), prev = [now-14d, now-7d)
func (q *Queries) GetMetrics(ctx context.Context, arg GetMetricsParams) (GetMetricsRow, error) {
	row := q.db.QueryRow(ctx, getMetrics,
		arg.WebsiteID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.CreatedAt_3,
		arg.CreatedAt_4,
	)
	var i GetMetricsRow
	err := row.Scan(
		&i.Visitors,
		&i.Visits,
		&i.Views,
		&i.AvgDurationSeconds,
		&i.PrevVisitors,
		&i.PrevVisits,
		&i.PrevViews,
		&i.PrevAvgDurationSeconds,
	)
	return i, err
}
