// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getChartDataByHour = `-- name: GetChartDataByHour :many
SELECT
  gs.period_start AS time,
  COUNT(p.id)::bigint AS views,
  COUNT(DISTINCT p.visitor_id)::bigint AS visitors
FROM generate_series(
  $2::timestamptz,
  $3::timestamptz,
  interval '1 hour'
) AS gs(period_start)
LEFT JOIN pageviews p
  ON p.website_id = $1
  AND p.created_at >= gs.period_start
  AND p.created_at <  gs.period_start + interval '1 hour'
  AND p.created_at >= $2::timestamptz
  AND p.created_at <= $3::timestamptz
GROUP BY gs.period_start
ORDER BY gs.period_start
`

type GetChartDataByHourParams struct {
	WebsiteID uuid.UUID
	Column2   time.Time
	Column3   time.Time
}

type GetChartDataByHourRow struct {
	Time     interface{}
	Views    int64
	Visitors int64
}

func (q *Queries) GetChartDataByHour(ctx context.Context, arg GetChartDataByHourParams) ([]GetChartDataByHourRow, error) {
	rows, err := q.db.Query(ctx, getChartDataByHour, arg.WebsiteID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChartDataByHourRow
	for rows.Next() {
		var i GetChartDataByHourRow
		if err := rows.Scan(&i.Time, &i.Views, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetrics = `-- name: GetMetrics :one
WITH current_period_visits AS (
    SELECT 
        COUNT(DISTINCT v.visitor_id)::bigint AS total_visitors,
        COUNT(v.id)::bigint AS total_visits,
        COALESCE(AVG(EXTRACT(EPOCH FROM (v.ended_at - v.started_at))), 0)::integer AS avg_visit_duration
    FROM visits v
    WHERE v.website_id = $1 
      AND v.started_at >= $2 AND v.started_at <= $3
),
current_period_views AS (
    SELECT COUNT(p.id)::bigint AS total_views
    FROM pageviews p
    WHERE p.website_id = $1 
      AND p.created_at >= $2 AND p.created_at <= $3
),
prev_period_visits AS (
    SELECT 
        COUNT(DISTINCT v.visitor_id)::bigint AS total_visitors,
        COUNT(v.id)::bigint AS total_visits,
        COALESCE(AVG(EXTRACT(EPOCH FROM (v.ended_at - v.started_at))), 0)::integer AS avg_visit_duration
    FROM visits v
    WHERE v.website_id = $1 
      AND v.started_at >= $4 AND v.started_at <= $5
),
prev_period_views AS (
    SELECT COUNT(p.id)::bigint AS total_views
    FROM pageviews p
    WHERE p.website_id = $1 
      AND p.created_at >= $4 AND p.created_at <= $5
)
SELECT 
    cvs.total_visitors AS "TotalVisitors",
    cvs.total_visits AS "TotalVisits",
    cvw.total_views AS "TotalViews",
    cvs.avg_visit_duration AS "AvgVisitDuration",
    pvs.total_visitors AS "PrevTotalVisitors",
    pvs.total_visits AS "PrevTotalVisits",
    pvw.total_views AS "PrevTotalViews",
    pvs.avg_visit_duration AS "PrevAvgVisitDuration"
FROM 
    current_period_visits cvs, 
    current_period_views cvw, 
    prev_period_visits pvs, 
    prev_period_views pvw
`

type GetMetricsParams struct {
	WebsiteID   uuid.UUID
	StartedAt   time.Time
	StartedAt_2 time.Time
	StartedAt_3 time.Time
	StartedAt_4 time.Time
}

type GetMetricsRow struct {
	TotalVisitors        int64
	TotalVisits          int64
	TotalViews           int64
	AvgVisitDuration     int32
	PrevTotalVisitors    int64
	PrevTotalVisits      int64
	PrevTotalViews       int64
	PrevAvgVisitDuration int32
}

func (q *Queries) GetMetrics(ctx context.Context, arg GetMetricsParams) (GetMetricsRow, error) {
	row := q.db.QueryRow(ctx, getMetrics,
		arg.WebsiteID,
		arg.StartedAt,
		arg.StartedAt_2,
		arg.StartedAt_3,
		arg.StartedAt_4,
	)
	var i GetMetricsRow
	err := row.Scan(
		&i.TotalVisitors,
		&i.TotalVisits,
		&i.TotalViews,
		&i.AvgVisitDuration,
		&i.PrevTotalVisitors,
		&i.PrevTotalVisits,
		&i.PrevTotalViews,
		&i.PrevAvgVisitDuration,
	)
	return i, err
}
