// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Pageview struct {
	ID         uuid.UUID
	WebsiteID  uuid.UUID
	VisitorID  uuid.UUID
	VisitID    uuid.UUID
	Path       string
	Referrer   string
	Browser    string
	Os         string
	DeviceType string
	Country    string
	CreatedAt  time.Time
}

type User struct {
	ID        uuid.UUID
	FullName  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserSession struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	ExpiresAt        time.Time
	CreatedAt        time.Time
}

type Visit struct {
	ID        uuid.UUID
	WebsiteID uuid.UUID
	VisitorID uuid.UUID
	Referrer  string
	StartedAt time.Time
	EndedAt   time.Time
}

type Visitor struct {
	ID          uuid.UUID
	WebsiteID   uuid.UUID
	VisitorHash string
	Country     string
	FirstSeen   time.Time
	LastSeen    time.Time
}

type Website struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Domain    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
