// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pageviews.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addPageview = `-- name: AddPageview :one
INSERT INTO pageviews (website_id, visitor_id, visit_id, path, referrer, browser, os, device_type, country)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, website_id, visitor_id, visit_id, path, referrer, browser, os, device_type, country, created_at
`

type AddPageviewParams struct {
	WebsiteID  uuid.UUID
	VisitorID  uuid.UUID
	VisitID    uuid.UUID
	Path       string
	Referrer   string
	Browser    string
	Os         string
	DeviceType string
	Country    string
}

func (q *Queries) AddPageview(ctx context.Context, arg AddPageviewParams) (Pageview, error) {
	row := q.db.QueryRow(ctx, addPageview,
		arg.WebsiteID,
		arg.VisitorID,
		arg.VisitID,
		arg.Path,
		arg.Referrer,
		arg.Browser,
		arg.Os,
		arg.DeviceType,
		arg.Country,
	)
	var i Pageview
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.VisitorID,
		&i.VisitID,
		&i.Path,
		&i.Referrer,
		&i.Browser,
		&i.Os,
		&i.DeviceType,
		&i.Country,
		&i.CreatedAt,
	)
	return i, err
}
