// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visitors.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addVisitor = `-- name: AddVisitor :one
INSERT INTO visitors (website_id, visitor_hash, country)
VALUES ($1, $2, $3)
RETURNING id, website_id, visitor_hash, country, first_seen, last_seen
`

type AddVisitorParams struct {
	WebsiteID   uuid.UUID
	VisitorHash string
	Country     string
}

func (q *Queries) AddVisitor(ctx context.Context, arg AddVisitorParams) (Visitor, error) {
	row := q.db.QueryRow(ctx, addVisitor, arg.WebsiteID, arg.VisitorHash, arg.Country)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.VisitorHash,
		&i.Country,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const getVisitorByHash = `-- name: GetVisitorByHash :one
SELECT id, website_id, visitor_hash, country, first_seen, last_seen
FROM visitors
WHERE website_id = $1 AND visitor_hash = $2
`

type GetVisitorByHashParams struct {
	WebsiteID   uuid.UUID
	VisitorHash string
}

func (q *Queries) GetVisitorByHash(ctx context.Context, arg GetVisitorByHashParams) (Visitor, error) {
	row := q.db.QueryRow(ctx, getVisitorByHash, arg.WebsiteID, arg.VisitorHash)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.VisitorHash,
		&i.Country,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}
