// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visits.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addVisit = `-- name: AddVisit :one
INSERT INTO visits (website_id, visitor_id, referrer)
VALUES ($1, $2, $3)
RETURNING id, website_id, visitor_id, referrer, started_at, ended_at
`

type AddVisitParams struct {
	WebsiteID uuid.UUID
	VisitorID uuid.UUID
	Referrer  string
}

func (q *Queries) AddVisit(ctx context.Context, arg AddVisitParams) (Visit, error) {
	row := q.db.QueryRow(ctx, addVisit, arg.WebsiteID, arg.VisitorID, arg.Referrer)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.VisitorID,
		&i.Referrer,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getVisitByID = `-- name: GetVisitByID :one
SELECT id, website_id, visitor_id, referrer, started_at, ended_at
FROM visits WHERE id = $1
`

func (q *Queries) GetVisitByID(ctx context.Context, id uuid.UUID) (Visit, error) {
	row := q.db.QueryRow(ctx, getVisitByID, id)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.VisitorID,
		&i.Referrer,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const updateVisitEndedAt = `-- name: UpdateVisitEndedAt :exec
UPDATE visits SET ended_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) UpdateVisitEndedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateVisitEndedAt, id)
	return err
}
