// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: websites.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addWebsite = `-- name: AddWebsite :one
INSERT INTO websites (user_id, name, domain)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, domain, created_at
`

type AddWebsiteParams struct {
	UserID uuid.UUID
	Name   string
	Domain string
}

type AddWebsiteRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Domain    string
	CreatedAt time.Time
}

func (q *Queries) AddWebsite(ctx context.Context, arg AddWebsiteParams) (AddWebsiteRow, error) {
	row := q.db.QueryRow(ctx, addWebsite, arg.UserID, arg.Name, arg.Domain)
	var i AddWebsiteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebsiteByID = `-- name: DeleteWebsiteByID :exec
DELETE FROM websites WHERE id = $1
`

func (q *Queries) DeleteWebsiteByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebsiteByID, id)
	return err
}

const getWebsiteByID = `-- name: GetWebsiteByID :one
SELECT id, user_id, name, domain, created_at FROM websites WHERE id = $1
`

type GetWebsiteByIDRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Domain    string
	CreatedAt time.Time
}

func (q *Queries) GetWebsiteByID(ctx context.Context, id uuid.UUID) (GetWebsiteByIDRow, error) {
	row := q.db.QueryRow(ctx, getWebsiteByID, id)
	var i GetWebsiteByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const getWebsitesByUserID = `-- name: GetWebsitesByUserID :many
SELECT id, user_id, name, domain, created_at FROM websites WHERE user_id = $1
`

type GetWebsitesByUserIDRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Domain    string
	CreatedAt time.Time
}

func (q *Queries) GetWebsitesByUserID(ctx context.Context, userID uuid.UUID) ([]GetWebsitesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getWebsitesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWebsitesByUserIDRow
	for rows.Next() {
		var i GetWebsitesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Domain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebsiteByID = `-- name: UpdateWebsiteByID :exec
UPDATE websites SET name = $1, domain = $2 WHERE id = $3
`

type UpdateWebsiteByIDParams struct {
	Name   string
	Domain string
	ID     uuid.UUID
}

func (q *Queries) UpdateWebsiteByID(ctx context.Context, arg UpdateWebsiteByIDParams) error {
	_, err := q.db.Exec(ctx, updateWebsiteByID, arg.Name, arg.Domain, arg.ID)
	return err
}
